In [1]:
import numpy as np
import pandas as pd
from pandas.io.excel import ExcelWriter
import os

# Настройки кол-ва записей в таблицах

In [2]:
# Count of data in every table
max_count_customer: int = 100
max_count_product_inst: int = 100
max_count_costed_event: int = 10485
max_count_costed_charge: int= 1233
max_count_costed_payment: int = 12442

# Product

In [3]:
path_Product = "csv/Product.csv"
ProductDf = pd.read_csv(path_Product, delimiter=',')
ProductDf.set_index('product_id', inplace=True)

# Count of data in Product table
max_count_product = ProductDf.shape[0]

# Customer

In [3]:
# ---
# 1. Create dataframe - Customer
path_Customer = "file.xlsx"

customer_id_PK: list = [i for i in range(1, max_count_customer)]
CustomerDf = pd.DataFrame(
    {
        "customer_id": pd.Series(customer_id_PK, name="customer_id", dtype="int"),
        # Add other columns here...
    }
)
CustomerDf.set_index('customer_id', inplace=True)

# Product_instance

In [ ]:
path_Product_instance = "file.xlsx"

# ---
# 3. Create dataframe - Product_instance
product_instance_id_PK: list  = [i for i in range(1, max_count_product_inst)]
customer_id_FK: list  = np.random.randint(1, max_count_customer, size=max_count_product_inst - 1)
product_id_FK: list  = np.random.randint(1, max_count_product, size=max_count_product_inst - 1) 
Product_instanceDf = pd.DataFrame(
    {
        "product_instance_id_PK": pd.Series(product_instance_id_PK, name="product_instance_id_PK", dtype="int"),
        "customer_id_FK": pd.Series(customer_id_FK, name="customer_id_FK", dtype="int"),
        "product_id_FK": pd.Series(product_id_FK, name="product_id_FK", dtype="int"),
        # Add other columns here...
    }
)
Product_instanceDf.set_index('product_instance_id_PK', inplace=True)

# Costed_event

In [8]:
path_Costed_event = "file.xlsx"

# ---
# 4. Create dataframe - Costed_event
event_types = ['call', 'sms', 'data']
direction_variations = ['incoming', 'outgoing']

# ---
# Generation columns for dataset 
event_id_PK: list  = [i for i in range(1, max_count_costed_event)] 
product_instance_id_FK_from_ce: list  = np.random.randint(1, max_count_product_inst, size=max_count_costed_event - 1)

# From
calling_msisdn: list = np.random.randint(1, max_count_customer, size=max_count_costed_event - 1)

# To
called_msisdn = []
for i in range(len(calling_msisdn)):
    called_msisdn_el = np.random.randint(1, max_count_customer)
    while i == called_msisdn:
        called_msisdn_el = np.random.randint(1, max_count_customer)
    called_msisdn.append(called_msisdn_el)

# Event type
event_type = np.random.choice(event_types, size=max_count_costed_event-1, p=[0.6, 0.15, 0.25])

# Direction
direction = np.random.choice(direction_variations, size=max_count_costed_event-1)

# Roaming
roaming = np.random.choice([0, 1], size=max_count_costed_event-1, p=[0.7, 0.3])



date = []

number_of_sms = []
total_volume = []



duration = []
cost = []
for i in range(max_count_costed_event - 1):
    pass


Costed_eventDf = pd.DataFrame(
    {
        "event_id_PK": pd.Series(event_id_PK, name="event_id_PK", dtype="int"),
        "product_instance_id_FK": pd.Series(product_instance_id_FK_from_ce, name="product_instance_id_FK", dtype="int"),
        

        "calling_msisdn": pd.Series(calling_msisdn, name="calling_msisdn", dtype="int"),
        "called_msisdn": pd.Series(called_msisdn, name="called_msisdn", dtype="int"),

        # "date": [1, 2, 3, 4, 5],
        # "cost": [1, 2, 3, 4, 5],
        # "duration": [1, 2, 3, 4, 5],
        # "number_of_sms": [1, 2, 3, 4, 5],
        # "total_volume": [1, 2, 3, 4, 5],
        "event_type": pd.Series(event_type, name="event_type", dtype="str"),
        "direction": pd.Series(direction, name="direction", dtype="str"),
        "roaming": pd.Series(roaming, name="roaming", dtype="int"),
        
        # Add other columns here...
    }
)
Costed_eventDf.set_index('event_id_PK', inplace=True)
Costed_eventDf

,product_instance_id_FK,calling_msisdn,called_msisdn,event_type,direction,roaming
event_id_PK,,,,,,
1,80,97,45,sms,incoming,1
2,5,42,19,call,outgoing,0
3,25,76,8,data,outgoing,0
4,92,65,58,call,outgoing,0
5,59,24,87,call,incoming,0
...,...,...,...,...,...,...
10480,70,84,45,call,incoming,0
10481,98,3,12,call,outgoing,1
10482,18,87,82,sms,incoming,0
10483,89,38,22,data,incoming,0
10484,73,9,22,sms,incoming,1

# Charge

In [ ]:
path_Charge = "file.xlsx"

# ---
# 5. Create dataframe - Charge
charge_id_PK: list  = [i for i in range(1, max_count_costed_charge)] 
product_instance_id_FK_charge: list   = np.random.randint(1, max_count_product_inst, size=max_count_costed_charge - 1)
ChargeDf = pd.DataFrame(
    {
        "charge_id_PK": pd.Series(charge_id_PK, name="charge_id_PK", dtype="int"),
        "product_instance_id_FK": pd.Series(product_instance_id_FK_charge, name="product_instance_id_FK", dtype="int"),
        # Add other columns here...
    }
)
ChargeDf.set_index('charge_id_PK', inplace=True)

# Payment

In [ ]:
path_Payment = "file.xlsx"

# ---
# 6. Create dataframe - Payment
payment_id_PK: list  = [i for i in range(1, max_count_costed_payment)]
customer_id_FK_in_payment: list = np.random.randint(1, max_count_customer, size=max_count_costed_payment - 1)
PaymentDf = pd.DataFrame(
    {
        "payment_id_PK": pd.Series(payment_id_PK, name="payment_id_PK", dtype="int"),
        "customer_id_FK": pd.Series(customer_id_FK_in_payment, name="customer_id_FK", dtype="int"),
        # Add other columns here...
    }
)
PaymentDf.set_index('payment_id_PK', inplace=True)

In [ ]:

# # ---
# # Save to EXCEL
# with ExcelWriter(path, mode="a" if os.path.exists(path) else "w") as writer:
#     CustomerDf.to_excel(writer, sheet_name="Customer")
#     ProductDf.to_excel(writer, sheet_name="Product")
#     Product_instanceDf.to_excel(writer, sheet_name="Product_instanc")
#     Costed_eventDf.to_excel(writer, sheet_name="Costed_event")
#     ChargeDf.to_excel(writer, sheet_name="Charge")
#     PaymentDf.to_excel(writer, sheet_name="Payment")